services:
  mysql:
    image: 'mysql:latest'
    env_file:
      - docker.env
    ports:
      - '3306'
  energ_os:
    image: pivoluz/api_relatorio_os
    env_file:
      - docker.env
    depends_on:
      - mysql
    ports:
      - '8080'