services:
  mysql:
    image: mysql:latest
    env_file:
      - .env
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - mysql_data:/var/lib/mysql
  energ_os:
    image: pivoluz/api_relatorio_os
    env_file:
      - .env
    depends_on:
      - mysql
    ports:
      - '${API_OS_PORT}:${API_OS_PORT}'
  email_os:
    image: pivoluz/api_email_os
    env_file:
      - .env
    ports:
      - '${API_EMAIL_PORT}:${API_EMAIL_PORT}'
volumes:
  mysql_data: