services:
  mysql:
    image: mysql:latest
    env_file:
      - .env
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - mysql_data:/var/lib/mysql

  energ_os:
    image: pivoluz/api_relatorio_os
    env_file:
      - .env
    depends_on:
      - mysql
    ports:
      - '${API_OS_PORT}:${API_OS_PORT}'

  api_ts:
    image: vidallluan/api-rest-energ
    env_file:
      - .env
    depends_on:
      - mysql
    ports:
      - '${PORT}:${PORT}'

  postgres:
    image: postgres:15.6
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  keycloak_web:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak_web
    env_file:
      - .env
    command: start-dev
    depends_on:
      - postgres
    ports:
      - '${KC_SERVER_PORT}:${KC_SERVER_PORT}'

volumes:
  mysql_data:
  postgres_data:
