spring:
  application:
    name: order_service
#  config:
#    import: file:.env[.properties]

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${MYSQL_DATABASE}?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

server:
  port: ${SERVER_PORT}

#logging:
#  level:
#    root: DEBUG

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://${KEYCLOAK_HOST}:8080/realms/${KEYCLOAK_REALM}
#          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
#
#jwt:
#  auth:
#    converter:
#      resource-id: energ_client_app
#      principle-attribute: preferred_username